### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by adahox** [opentibia/server#42]
how can i compile the source?

**Comment by iryont** [comment]
What kind of operating system are you using?

**Comment by adahox** [comment]
ya. actualy i'm usying windows. will i need some lib? or just open the open tibia project and compile?

**Comment by iryont** [comment]
Unfortunately you will need several libraries to make it work. Please have a look:

https://github.com/opentibia/server/wiki/Compiling-OTServ-0.7.0-under-Windows-using-MinGW

**Comment by adahox** [comment]
alright. thanks iryont :D

**Comment by adahox** [comment]
sorry but i'm getting some error. i googled so hard but i dont find anything helpfull. someone already get this error: 
src\otpch.h	[Error] libxml/xmlmemory.h: No such file or directory

i dont know here find this file. i downloaded all the libraries.

**Comment by OsoSangre** [comment]
My knowledge is a little dated, but you'll need:
* iconv.dll
* libmysql.dll
* libxml2.dll
* zlib1.dll
* mingwm10.dll
* boost_thread-mgw34-mt-1_35.dll (not sure if we are using a newer version)
* boost_system-mgw34-mt-1_35.dll (not sure if we are using a newer version)

**Comment by adahox** [comment]
ya. exactly. i already downloaded all libs but i dont know how to link it on the project.

**Comment by iryont** [comment]
Do you have libxml in your include/ directory of MinGW or whatever are you using?

**Comment by adahox** [comment]
ya. i've libxml and others libs. lock the error in this link:

http://imageshack.com/a/img538/5311/3sonCM.png

**Comment by iryont** [comment]
You should use cmake as generator for your build files. You can't really add files to Dev-C++ project and expect them to work :(

**Comment by adahox** [comment]
omg iryont. sorry. i dont know how to use cmake :(

**Comment by ivucica** [comment]
This is not a bug with the OpenTibia Server. It's fairly inappropriate to use the GitHub bug system as a support board. 

- If you have a specific bug with the code that you have to report, please open a new bug. 
- If you have instructions you'd like to post, please update the wiki. 
- If you have a patch for the codebase, please create a pull request.
- If you need assistance, there are various OT-related forums on the web.

**Comment by iryont** [comment]
@ivucica  is correct. However, I see no problem in a small support due to pretty much dead users base.

In any case you need to add MinGW to system path:

http://stackoverflow.com/questions/5733220/how-to-add-mingw-bin-directory-to-my-system-path

The next thing you have to do is to follow this tutorial:

https://github.com/opentibia/server/wiki/Compiling-OTServ-0.7.0-under-Windows-using-MinGW

**Comment by assassina** [comment]
I've noticed that the readme file doesn't include instructions about how to compile. Maybe we should include it in there, as well as a direct link for download of the latest version in trevis (for those who are too noob - or too lazy - to learn how to compile).

**Comment by adahox** [comment]
ya. do it man. i'm a noob. i dont know how to compile this source. really. it is so hard

**Comment by iryont** [comment]
I have to agree with @assassina, but in order to create automatic builds I had to implement static linking for the executable. It should be working now.

Travis is having some kind of issue with static linking (related to pthread) - I will have a look later on.
